"""initialdb

Revision ID: 05d8065d1e69
Revises: 
Create Date: 2022-11-24 23:47:38.202710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d8065d1e69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('title', sa.TEXT(), nullable=True))
    op.add_column('letters', sa.Column('date_sent', sa.DateTime(timezone=True), nullable=True))
    op.add_column('schedules', sa.Column('letter_id', sa.Integer(), nullable=True))
    op.add_column('schedules', sa.Column('completed', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'schedules', 'letters', ['letter_id'], ['id'])
    op.drop_column('subscriptions', 'total_sms')
    op.add_column('users', sa.Column('plan_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('free_trial', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'free_trial')
    op.drop_column('users', 'plan_type')
    op.add_column('subscriptions', sa.Column('total_sms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'completed')
    op.drop_column('schedules', 'letter_id')
    op.drop_column('letters', 'date_sent')
    op.drop_column('letters', 'title')
    # ### end Alembic commands ###
