"""Initial migration


Revision ID: 890f7b7e6273
Revises: d4f574435bdf
Create Date: 2022-11-24 15:37:01.831886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890f7b7e6273'
down_revision = 'd4f574435bdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('title', sa.TEXT(), nullable=True))
    op.drop_column('subscriptions', 'total_sms')
    op.add_column('users', sa.Column('plan_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan_type')
    op.add_column('subscriptions', sa.Column('total_sms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('letters', 'title')
    # ### end Alembic commands ###
